"""Validate the Claude Code plugin marketplace artifacts.

The repo doubles as a Claude Code plugin marketplace: `.claude-plugin/marketplace.json`
(hand-authored) points at `plugins/life-planning-coach/` (generated by
`scripts/build-skill.py build`, same pattern as `platforms/`). Users install via:
    /plugin marketplace add azagreev/life-planning-coach

These tests guard that the committed manifests are valid AND that the generated
plugin tree stays in sync with the source skill + references (so a stale plugin
— refs changed but not rebuilt — is caught in CI, not shipped to users).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
MARKETPLACE = PROJECT_ROOT / ".claude-plugin" / "marketplace.json"
PLUGIN_DIR = PROJECT_ROOT / "plugins" / "life-planning-coach"
PLUGIN_JSON = PLUGIN_DIR / ".claude-plugin" / "plugin.json"
PLUGIN_SKILL_DIR = PLUGIN_DIR / "skills" / "life-planning-coach"

# Dev-only references excluded from the shipped skill (mirror build-skill.py).
REFERENCES_EXCLUDE_DIRS = {"research", "tasks", "archive"}
REFERENCES_EXCLUDE_PREFIXES = (
    "acceptance_criteria_",
    "plan_v",
    "release_checklist_",
    "persistence_research_plan",
    "research_",
)


def _skill_master_version() -> str:
    master = (PROJECT_ROOT / "SKILL.master.md").read_text(encoding="utf-8")
    m = re.search(r"^version:\s*(\S+)\s*$", master, re.MULTILINE)
    assert m, "version not found in SKILL.master.md frontmatter"
    return m.group(1).strip("\"'")


# ----- marketplace.json --------------------------------------------------


def test_marketplace_json_valid():
    assert MARKETPLACE.exists(), f"{MARKETPLACE} missing"
    data = json.loads(MARKETPLACE.read_text(encoding="utf-8"))
    assert data.get("name"), "marketplace.json needs a name"
    assert data.get("owner", {}).get("name"), "marketplace.json needs owner.name"
    assert isinstance(data.get("plugins"), list) and data["plugins"], "plugins[] must be non-empty"


def test_marketplace_entry_source_resolves():
    data = json.loads(MARKETPLACE.read_text(encoding="utf-8"))
    entry = next((p for p in data["plugins"] if p.get("name") == "life-planning-coach"), None)
    assert entry, "marketplace.json must list the life-planning-coach plugin"
    source = entry.get("source")
    assert source, "plugin entry needs a source"
    # source is relative to the marketplace root (repo root)
    resolved = (PROJECT_ROOT / source).resolve()
    assert resolved == PLUGIN_DIR.resolve(), f"source '{source}' must point to plugins/life-planning-coach"
    assert resolved.is_dir(), f"plugin source dir {resolved} does not exist"


# ----- plugin.json -------------------------------------------------------


def test_plugin_json_valid():
    assert PLUGIN_JSON.exists(), f"{PLUGIN_JSON} missing (run: python scripts/build-skill.py build)"
    data = json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))
    assert data.get("name") == "life-planning-coach", "plugin.json name must be life-planning-coach"
    assert data.get("license") == "MIT", "plugin.json license should be MIT (repo LICENSE)"


def test_plugin_version_matches_skill():
    data = json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))
    assert data.get("version") == _skill_master_version(), (
        "plugin.json version is stale — run `python scripts/build-skill.py build` "
        "so it matches SKILL.master.md"
    )


# ----- generated skill tree ---------------------------------------------


def test_plugin_skill_present():
    assert (PLUGIN_SKILL_DIR / "SKILL.md").exists(), "plugin skill SKILL.md missing"


def test_plugin_skill_in_sync_with_root():
    """Plugin skill is a copy of the root (Claude) SKILL.md — must be byte-identical."""
    plugin_skill = (PLUGIN_SKILL_DIR / "SKILL.md").read_bytes()
    root_skill = (PROJECT_ROOT / "SKILL.md").read_bytes()
    assert plugin_skill == root_skill, (
        "plugins/.../SKILL.md is out of sync with root SKILL.md — "
        "run `python scripts/build-skill.py build`"
    )


def test_plugin_references_in_sync_with_source():
    """Every reference shipped in the plugin must byte-match its source under references/."""
    plugin_refs = PLUGIN_SKILL_DIR / "references"
    assert plugin_refs.is_dir(), "plugin references/ dir missing"
    stale = []
    for f in plugin_refs.rglob("*"):
        if not f.is_file():
            continue
        rel = f.relative_to(plugin_refs)
        src = PROJECT_ROOT / "references" / rel
        if not src.exists() or src.read_bytes() != f.read_bytes():
            stale.append(str(rel))
    assert not stale, (
        f"plugin references out of sync with references/ (run build): {stale[:5]}"
    )


def test_plugin_excludes_dev_only_references():
    """Dev-only references must NOT ship in the plugin (no test/research/task cruft)."""
    plugin_refs = PLUGIN_SKILL_DIR / "references"
    offenders = []
    for f in plugin_refs.rglob("*"):
        if not f.is_file():
            continue
        parts = set(f.relative_to(plugin_refs).parts)
        if parts & REFERENCES_EXCLUDE_DIRS:
            offenders.append(str(f.relative_to(plugin_refs)))
        elif any(f.name.startswith(p) for p in REFERENCES_EXCLUDE_PREFIXES):
            offenders.append(str(f.relative_to(plugin_refs)))
    assert not offenders, f"dev-only references leaked into plugin: {offenders[:5]}"
